from enum import Enum


class LearningRateScheduler(Enum):
    CONSTANT = 'CONSTANT'
    COSINE = 'COSINE'
    COSINE_WITH_HARD_RESTARTS = 'COSINE_WITH_HARD_RESTARTS'
    REX = 'REX'
    TRIANGLE = 'TRIANGLE'
    RAMP = 'RAMP'
    SAWTOOTH = 'SAWTOOTH'
    SQUARE = 'SQUARE'
    PULSE = 'PULSE'
    ROUNDED_PULSE = 'ROUNDED_PULSE'
    TRIANGLE_PULSE = 'TRIANGLE_PULSE'
    RAMP_PULSE = 'RAMP_PULSE'
    SAWTOOTH_PULSE = 'SAWTOOTH_PULSE'
    SINE_CUBED = 'SINE_CUBED'
    FLAME = 'FLAME'
    SEMICIRCLE = 'SEMICIRCLE'

    def __str__(self):
        return self.value
